### ISSUE TITLE
Update readme cch to custom_header:

### ISSUE THREAD

**Issue by KShips** [basnijholt/lovelace-ios-dark-mode-theme#18]
Since cch was replaced with Custom Header, step 4 needs to be updated from cch to custom_header.

Edit, clock didn't work either so I have updated code to fix. 

**Change**
```
cch:
  background: rgba(155, 155, 155, 0.25)
  clock_format: 24
  options: clock
  swipe_animate: fade
  swipe_prevent_default: true
```
**to**
```
custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  swipe_animate: fade
  swipe_prevent_default: true
  compact_mode: true
  button_text:
    options: '{{ hours12 }}:{{ minutesLZ }}'
```
