### ISSUE TITLE
Wrong colors with vertical-stack-in-card

### ISSUE THREAD

**Issue by bieniu** [basnijholt/lovelace-ios-dark-mode-theme#21]
I use vertical-stack-in-card to join glance and entities cards. Your theme colors are wrong with that configuration. There is difference between title background color and card background color. And the color of the gap between glance and entities card is wrong.
```
         - type: custom:vertical-stack-in-card
            title: "Sypialnia"
            cards:
              - type: glance
                show_name: false
                entities:
                  - sensor.temperature_sypialnia
                  - sensor.humidity_sypialnia
                  - sensor.illumination_sypialnia
              - type: entities
                style: |
                  .card-content {
                    padding-top: 0px;
                  }
                show_header_toggle: false
                entities:
                  - binary_sensor.window_sypialnia
                  - binary_sensor.balcony_door_sypialnia
                  - entity: binary_sensor.motion_sypialnia
                    secondary_info: last-changed
                  - climate.thermostat_sypialnia
                  - light.lightstrip_sypialnia
                  - switch.christmas_lights_sypialnia
```
![image](https://user-images.githubusercontent.com/478555/72637834-72927300-3962-11ea-815c-8062d4351001.png)
