### ISSUE TITLE
Background image doesn't fill page

### ISSUE THREAD

**Issue by D-an-W** [basnijholt/lovelace-ios-dark-mode-theme#28]
Good morning, just discovered these themes and love them.

One thing I have seen though is I am left with a border (The width of the header / footer) at the bottom of the screen on my 1920x1200 display.

If I enable split mode in Custom Header this goes away as it is filled by the footer (It also goes away if I move the header to the bottom but then can't scroll in certain menus).

![Screenshot 2020-01-30 at 06 53 37](https://user-images.githubusercontent.com/2243883/73426839-4a751d80-432d-11ea-9e1a-9ecc98ff644b.png)

Any ideas what I might be doing wrong please?

**Comment by basnijholt** [comment]
Did you follow **all** of the steps?

In particular, step 2.

**Comment by D-an-W** [comment]
Hi @basnijholt, I think everything is ok with what I did. I see this at the top when I open the RAW Config Editor...

`background: var(--background-image)
custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'
  compact_mode: true
  swipe_animate: fade
  swipe_prevent_default: true
resources:
  - type: module
    url: /community_plugin/custom-header/custom-header.js`

**Comment by D-an-W** [comment]
Yes I think I did, here is how it looks in the RAW Config Editor...

```
resources:
  - url: /community_plugin/custom-header/custom-header.js
    type: module
background: var(--background-image)
custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  compact_mode: true
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'
```

It may also of course be an issue with Custom Header itself?
