### ISSUE TITLE
problem of theme in HASSIO 0.107.6

### ISSUE THREAD

**Issue by pilot1981** [basnijholt/lovelace-ios-dark-mode-theme#38]
Hi,
I have Home Assistant 0.107.6 with your plugin installed via HACS:

<img width="642" alt="Schermata 2020-03-25 alle 22 46 16" src="https://user-images.githubusercontent.com/46350465/77588725-b79ace80-6eea-11ea-8caf-d53ce59e76b8.png">

and I obtained this result:

<img width="1217" alt="Schermata 2020-03-25 alle 22 45 55" src="https://user-images.githubusercontent.com/46350465/77588742-bff30980-6eea-11ea-90cc-7e3df0716e93.png">

but I'm not able to obtain result reported on your wiki:

<img width="911" alt="Schermata 2020-03-25 alle 22 47 26" src="https://user-images.githubusercontent.com/46350465/77588776-cf725280-6eea-11ea-9c71-030e3826b22f.png">

how I can do it?

**Comment by grahamr** [comment]
a couple steps you still need to do to get the same as in the sample (from the instructions)


Step 2. Add the following line to your lovelace-ui.yaml or use the RAW editor:
`background: var(--background-image)`

Step 3: (Optional) add the following to the same file to make the header smaller (you need to install custom-header too):
```
custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  compact_mode: true
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'
```

**Comment by pilot1981** [comment]
ok, thanks

Now all work fine on desktop version, but in app home assistant for IOS I see always default theme white&blue...

**Comment by njsaunders** [comment]
I'm having the same problem here I'm afraid, even with those lines added:

```
root@raspberrypi:/home/homeassistant/.homeassistant# ls -la
total 2376
drwxr-xr-x 8 homeassistant homeassistant    4096 Mar 31 16:04 .
drwxr-xr-x 4 homeassistant homeassistant    4096 Mar 31 12:53 ..
-rw-r--r-- 1 homeassistant homeassistant       2 Mar 31 12:53 automations.yaml
drwxr-xr-x 2 homeassistant homeassistant    4096 Mar 31 14:01 .cloud
-rw-r--r-- 1 homeassistant homeassistant     321 Mar 31 15:46 configuration.yaml
drwxr-xr-x 5 homeassistant homeassistant    4096 Mar 31 14:19 custom_components
drwxr-xr-x 2 homeassistant homeassistant    4096 Mar 31 12:53 deps
-rw-r--r-- 1 homeassistant homeassistant       0 Mar 31 12:53 groups.yaml
-rw-r--r-- 1 homeassistant homeassistant       7 Mar 31 12:53 .HA_VERSION
-rw-r--r-- 1 homeassistant homeassistant     825 Mar 31 16:08 home-assistant.log
-rw-r--r-- 1 homeassistant homeassistant 2371584 Mar 31 15:18 home-assistant_v2.db
-rw-r--r-- 1 homeassistant homeassistant     175 Mar 31 16:01 lovelace-ui.yaml
-rw-r--r-- 1 homeassistant homeassistant       0 Mar 31 12:53 scenes.yaml
-rw-r--r-- 1 homeassistant homeassistant       0 Mar 31 12:53 scripts.yaml
-rw-r--r-- 1 homeassistant homeassistant     161 Mar 31 12:53 secrets.yaml
drwxr-xr-x 2 homeassistant homeassistant    4096 Mar 31 16:09 .storage
drwxr-xr-x 3 homeassistant homeassistant    4096 Mar 31 16:08 themes
drwxr-xr-x 2 homeassistant homeassistant    4096 Mar 31 13:40 tts
```

And lovelace-ui.yaml:
```
root@raspberrypi:/home/homeassistant/.homeassistant# cat lovelace-ui.yaml
background: var(--background-image)

custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  compact_mode: true
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'
```

Would love to get it working - Beautiful looking theme!
